### PR TITLE
Fix minor issue with ie11

### PR DESCRIPTION
**Pull request by casperin**
In ie11, calling `.set(k, v)` on a map does not return the map for further chaining, so the construction in `hyphenateStyleName` threw an error every time in ie11. This PR should fix that, but otherwise leave the code completely unchanged.

## Types of changes

* [x] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

* [x] My code follows the code style of this project.
  * Thanks prettier
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have read the **CONTRIBUTING** document.
  * Can't find this
* [ ] I have added tests to cover my changes. 
* [x] All new and existing tests passed.

### CODE REVIEW

**Comment by frenzzy** [comment]
Thank you!

**Comment by casperin** [comment]
No problem. Keep up the good work. :-)

**Comment by casperin** [comment]
By the way, will you release this on its own? I can understand if you think it's too small -- if so I'll just keep using a local version.

**Comment by frenzzy** [comment]
Sure, just released under [v3.1.0](https://github.com/kriasoft/hyperapp-render/releases/tag/v3.1.0) :tada: thanks again.

**Pull request merged**
